# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20170507_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='details',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='details',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
