# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_auto_20170507_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
