# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_auto_20170509_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-create_date',)},
        ),
    ]
