# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_auto_20170510_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
