# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_answer_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(max_length=100)),
                ('number', models.IntegerField(default=1)),
                ('image', models.FileField(blank=True, upload_to=questions.models.instruction_image_uploadpath)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Answer')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
    ]
