# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer',
        ),
    ]
