# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0027_remove_answer_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instruction',
            options={'ordering': ['number']},
        ),
    ]
