# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0028_auto_20170516_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.FileField(blank=True, upload_to=questions.models.instruction_image_uploadpath),
        ),
    ]
