# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0036_auto_20170529_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.FileField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.CharField(default=b'description', max_length=200),
        ),
    ]
