# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0038_auto_20170529_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
